$seed_table = [{"Seed"=>"0", "Bloodline"=>nil, "Hair"=>"silver", "Eyes"=>"blue", "Misc"=>"weirdly sweaty"}, {"Seed"=>"100", "Bloodline"=>"waterbender clan", "Hair"=>"silver", "Eyes"=>"blue", "Misc"=>"weirdly sweaty"}, {"Seed"=>"200", "Bloodline"=>"boreal", "Hair"=>"silver", "Eyes"=>"blue", "Misc"=>"lower body temperature"}, {"Seed"=>"300", "Bloodline"=>"boreal", "Hair"=>"gray", "Eyes"=>"blue", "Misc"=>"lower body temperature"}, {"Seed"=>"400", "Bloodline"=>"forcemage clan", "Hair"=>"gray", "Eyes"=>"blue", "Misc"=>"big ears"}, {"Seed"=>"500", "Bloodline"=>nil, "Hair"=>"gray", "Eyes"=>"blue", "Misc"=>"big ears"}, {"Seed"=>"600", "Bloodline"=>nil, "Hair"=>"gray", "Eyes"=>"blue", "Misc"=>nil}, {"Seed"=>"700", "Bloodline"=>"Deep Earth", "Hair"=>"gray", "Eyes"=>"blue", "Misc"=>"short"}, {"Seed"=>"800", "Bloodline"=>"Deep earth ", "Hair"=>"gray", "Eyes"=>"blue", "Misc"=>"short"}, {"Seed"=>"900", "Bloodline"=>"Forge clan", "Hair"=>"gray", "Eyes"=>"blue", "Misc"=>"short"}, {"Seed"=>"1000", "Bloodline"=>nil, "Hair"=>"gray", "Eyes"=>"blue", "Misc"=>nil}, {"Seed"=>"1100", "Bloodline"=>nil, "Hair"=>"gray", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"1200", "Bloodline"=>nil, "Hair"=>"gray", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"1300", "Bloodline"=>nil, "Hair"=>"gray", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"1400", "Bloodline"=>nil, "Hair"=>"black", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"1500", "Bloodline"=>nil, "Hair"=>"black", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"1600", "Bloodline"=>"necrid clan", "Hair"=>"black", "Eyes"=>"green", "Misc"=>"Very gaunt"}, {"Seed"=>"1700", "Bloodline"=>"ectoplasm", "Hair"=>"wispy black", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"1800", "Bloodline"=>"ectoplasm", "Hair"=>"wispy black", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"1900", "Bloodline"=>"ghoul sorcerer", "Hair"=>"wispy black", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"2000", "Bloodline"=>"ghoul sorcerer", "Hair"=>"wispy black", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"2100", "Bloodline"=>"hag", "Hair"=>"wispy black", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"2200", "Bloodline"=>"hag", "Hair"=>"wispy black", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"2300", "Bloodline"=>nil, "Hair"=>"wispy black", "Eyes"=>"green", "Misc"=>nil}, {"Seed"=>"2400", "Bloodline"=>"Ph'tagn clan", "Hair"=>"albino", "Eyes"=>"strange", "Misc"=>"Extra finger joints"}, {"Seed"=>"2500", "Bloodline"=>"Bloodborne clan", "Hair"=>"black ", "Eyes"=>"brown", "Misc"=>"Port-wine birthmarks"}, {"Seed"=>"2600", "Bloodline"=>"Faust clan", "Hair"=>"black ", "Eyes"=>"red", "Misc"=>"Odd brimstone scent"}, {"Seed"=>"2700", "Bloodline"=>"abyssal", "Hair"=>"black ", "Eyes"=>"red", "Misc"=>nil}, {"Seed"=>"2800", "Bloodline"=>"abyssal", "Hair"=>"black ", "Eyes"=>"red", "Misc"=>nil}, {"Seed"=>"2900", "Bloodline"=>"daemon", "Hair"=>"black ", "Eyes"=>"red", "Misc"=>nil}, {"Seed"=>"3000", "Bloodline"=>"daemon", "Hair"=>"black ", "Eyes"=>"red", "Misc"=>nil}, {"Seed"=>"3100", "Bloodline"=>nil, "Hair"=>"black ", "Eyes"=>"red", "Misc"=>nil}, {"Seed"=>"3200", "Bloodline"=>nil, "Hair"=>"black ", "Eyes"=>"garnet-colored", "Misc"=>nil}, {"Seed"=>"3300", "Bloodline"=>nil, "Hair"=>"black ", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"3400", "Bloodline"=>nil, "Hair"=>"black ", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"3500", "Bloodline"=>"shadow", "Hair"=>"black ", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"3600", "Bloodline"=>"shadow", "Hair"=>"black ", "Eyes"=>"black", "Misc"=>nil}, {"Seed"=>"3700", "Bloodline"=>"dreamspun", "Hair"=>"black ", "Eyes"=>"black", "Misc"=>nil}, {"Seed"=>"3800", "Bloodline"=>"dreamspun", "Hair"=>"black ", "Eyes"=>"black", "Misc"=>nil}, {"Seed"=>"3900", "Bloodline"=>"psychic", "Hair"=>"black ", "Eyes"=>"black", "Misc"=>nil}, {"Seed"=>"4000", "Bloodline"=>"psychic", "Hair"=>"black ", "Eyes"=>"black", "Misc"=>"gnarly teeth"}, {"Seed"=>"4100", "Bloodline"=>"kitsune clan", "Hair"=>"black ", "Eyes"=>"black", "Misc"=>"Pale and slender"}, {"Seed"=>"4200", "Bloodline"=>"maestro", "Hair"=>"black ", "Eyes"=>"black", "Misc"=>"intense gaze"}, {"Seed"=>"4300", "Bloodline"=>"maestro", "Hair"=>"black ", "Eyes"=>"black", "Misc"=>nil}, {"Seed"=>"4400", "Bloodline"=>"fae clan", "Hair"=>"black ", "Eyes"=>"black", "Misc"=>"Hyperactive"}, {"Seed"=>"4500", "Bloodline"=>nil, "Hair"=>"black ", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"4600", "Bloodline"=>nil, "Hair"=>"red", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"4700", "Bloodline"=>nil, "Hair"=>"red", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"4800", "Bloodline"=>"starsoul", "Hair"=>"red", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"4900", "Bloodline"=>"starsoul", "Hair"=>"red", "Eyes"=>"gold", "Misc"=>nil}, {"Seed"=>"5000", "Bloodline"=>"efreeti", "Hair"=>"red", "Eyes"=>"gold", "Misc"=>nil}, {"Seed"=>"5100", "Bloodline"=>"efreeti", "Hair"=>"red", "Eyes"=>"gold", "Misc"=>nil}, {"Seed"=>"5200", "Bloodline"=>"dragonborn clan", "Hair"=>"bald", "Eyes"=>"gold", "Misc"=>"serpent scales"}, {"Seed"=>"5300", "Bloodline"=>"kobold", "Hair"=>"bald", "Eyes"=>"gold", "Misc"=>"serpent scales"}, {"Seed"=>"5400", "Bloodline"=>"kobold", "Hair"=>"bald", "Eyes"=>"yellow", "Misc"=>"serpent scales"}, {"Seed"=>"5500", "Bloodline"=>"serpentine", "Hair"=>"bald", "Eyes"=>"yellow", "Misc"=>"serpent scales"}, {"Seed"=>"5600", "Bloodline"=>"serpentine", "Hair"=>"bald", "Eyes"=>"yellow", "Misc"=>"serpent scales"}, {"Seed"=>"5700", "Bloodline"=>nil, "Hair"=>"blonde", "Eyes"=>"yellow", "Misc"=>"serpent scales"}, {"Seed"=>"5800", "Bloodline"=>nil, "Hair"=>"blonde", "Eyes"=>"yellow", "Misc"=>"serpent scales"}, {"Seed"=>"5900", "Bloodline"=>nil, "Hair"=>"blonde", "Eyes"=>"yellow", "Misc"=>nil}, {"Seed"=>"6000", "Bloodline"=>nil, "Hair"=>"blonde", "Eyes"=>"yellow", "Misc"=>nil}, {"Seed"=>"6100", "Bloodline"=>nil, "Hair"=>"platinum blonde", "Eyes"=>"gold", "Misc"=>nil}, {"Seed"=>"6200", "Bloodline"=>"Celestial", "Hair"=>"platinum blonde", "Eyes"=>"glowing golden", "Misc"=>nil}, {"Seed"=>"6300", "Bloodline"=>"celestial", "Hair"=>"platinum blonde", "Eyes"=>"glowing golden", "Misc"=>nil}, {"Seed"=>"6400", "Bloodline"=>"stormlord clan", "Hair"=>"platinum blonde", "Eyes"=>"glowing violet", "Misc"=>nil}, {"Seed"=>"6500", "Bloodline"=>"Djinni", "Hair"=>"platinum blonde", "Eyes"=>"violet", "Misc"=>nil}, {"Seed"=>"6600", "Bloodline"=>"Djinni", "Hair"=>"platinum blonde", "Eyes"=>"violet", "Misc"=>nil}, {"Seed"=>"6700", "Bloodline"=>"destined", "Hair"=>"platinum blonde", "Eyes"=>"violet", "Misc"=>nil}, {"Seed"=>"6800", "Bloodline"=>"destined", "Hair"=>"platinum blonde", "Eyes"=>"gray", "Misc"=>nil}, {"Seed"=>"6900", "Bloodline"=>nil, "Hair"=>"blonde", "Eyes"=>"gray", "Misc"=>nil}, {"Seed"=>"7000", "Bloodline"=>nil, "Hair"=>"blonde", "Eyes"=>"gray", "Misc"=>nil}, {"Seed"=>"7100", "Bloodline"=>nil, "Hair"=>"blonde", "Eyes"=>"gray", "Misc"=>nil}, {"Seed"=>"7200", "Bloodline"=>nil, "Hair"=>"blonde", "Eyes"=>"gray", "Misc"=>nil}, {"Seed"=>"7300", "Bloodline"=>"martyred", "Hair"=>"bald", "Eyes"=>"gray", "Misc"=>nil}, {"Seed"=>"7400", "Bloodline"=>"armorbonded clan", "Hair"=>"bald", "Eyes"=>"gray", "Misc"=>nil}, {"Seed"=>"7500", "Bloodline"=>"martyred", "Hair"=>"bald", "Eyes"=>"gray", "Misc"=>nil}, {"Seed"=>"7600", "Bloodline"=>nil, "Hair"=>"bald", "Eyes"=>"gray", "Misc"=>nil}, {"Seed"=>"7700", "Bloodline"=>nil, "Hair"=>"bald", "Eyes"=>"gray", "Misc"=>"gray tinge to skin"}, {"Seed"=>"7800", "Bloodline"=>"city-builder clan", "Hair"=>"bald", "Eyes"=>"gold", "Misc"=>"Part minotaur--see details"}, {"Seed"=>"7900", "Bloodline"=>"oni ", "Hair"=>"black", "Eyes"=>"gold", "Misc"=>"gray tinge to skin"}, {"Seed"=>"8000", "Bloodline"=>"oni ", "Hair"=>"black", "Eyes"=>"gold", "Misc"=>"gray tinge to skin"}, {"Seed"=>"8100", "Bloodline"=>"orc", "Hair"=>"black", "Eyes"=>"brown", "Misc"=>"gray tinge to skin"}, {"Seed"=>"8200", "Bloodline"=>"orc", "Hair"=>"bald", "Eyes"=>"brown", "Misc"=>"gray tinge to skin"}, {"Seed"=>"8300", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>"gray tinge to skin"}, {"Seed"=>"8400", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>"gray tinge to skin"}, {"Seed"=>"8500", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"8600", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"8700", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"8800", "Bloodline"=>nil, "Hair"=>"brown", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"8900", "Bloodline"=>"pestilence ", "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"9000", "Bloodline"=>"pestilence ", "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"9100", "Bloodline"=>"midwife clan", "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>"Uncannily average-looking"}, {"Seed"=>"9200", "Bloodline"=>"verdant", "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"9300", "Bloodline"=>"verdant", "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"9400", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"9500", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"brown", "Misc"=>nil}, {"Seed"=>"9600", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"blue", "Misc"=>nil}, {"Seed"=>"9700", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"blue", "Misc"=>nil}, {"Seed"=>"9800", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"blue", "Misc"=>nil}, {"Seed"=>"9900", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"blue", "Misc"=>nil}, {"Seed"=>"10000", "Bloodline"=>nil, "Hair"=>"Brown", "Eyes"=>"blue", "Misc"=>nil}]


$trait_dict = {
	"10" => "Clumsy: -2 Dex",
	"11" => "Bear Strength: +2 Str",
	"12" => "Slow: -10ft Move",
	"13" => "Brainy: +2 Int",
	"14" => "Dimwitted: -2 Int",
	"15" => "Fertile: + 1 Child",
	"16" => "Puny: -2 Str",
	"17" => "Hawk Eye: + 1 Atk",
	"18" => "Nearsighted: -1 Atk",
	"19"=>  "Sickly: -2 Con",
	"20" => "Light Frame: +10 Speed, -2 Con",
	"21" => "Fast: +10ft Move",
	"22" => "Strong Willed: +2 Wis",
	"23" => "Kingmaker: More male children",
	"24" => "Queenmaker: More female children",
	"25" => "Nimble: +2 Dex",
	"26" => "Willowy: +2 Dex, -3 Str",
	"27" => "High-energy: +2 CHA",
	"28" => "Low Fertility: -1 Child",
	"29" => "Brutish: +2 Str, -3 Dex",
	"30" => "Slow Learner: -50% XP gain",
	"31" => "Big-Boned: +2 Con, -3 Dex.",
	"32" => "Curious: +50% XP gain",
	"33" => "Hearty: +2 Con",
  "34" => "Impressionable: -2 Wis",
  "35" => "Sedate: -2 CHA",
}


$inbred_dict ={

	"0" => "Genius: +2 to all mental stats.",
	"1" => "Inbreeding Type 1: -2 to all physical stats",
	"2" => "Inbreeding Type 2: each child has a 50% chance of death.",
	"3" => "Hemophilia: -1 child, and every attack inflicts bleed damage.",
	"4" => "Dullard: -2 to all mental stats",
	"5" => "Fainting dog syndrome: cumulative 1/6 chance of passing out during combat.",
	"6" => "Weird birthmarks everywhere: spot spot spot.",
	"7" => "Imbecile: -4 to all mental stats",
	"8" => "Flipperhands: Flippers, instead of hands. You inbred too hard.",
	"9" => "Pygmy: Your size category is small, and you have -2 to all physical stats"
}

$quirk_dict = {
	"1" => "Alert: +1 AC",
	"2" => "Attuned: +2 Wis",
	"3" => "Berserker: Rage upon ally death",
	"4" => "Forgetful: -2 Int",
	"5" => "Bloodthirsty: temporary +1 Atk, Str, and Dex if vanquished an enemy recently",
	"6" => "NERD: +2 Int",
	"7" => "Brazen: +1 Atk",
	"8" => "Hates Children: -1 Child",
	"9" => "Clearheaded: +2 Wis",
	"10" => "Cocky: -1 AC, +1 CHA",
	"11" => "Chronic Depression: -2 Wis, -10 speed, -1 Child",
	"12" => "Quitter: -1 Atk, -1 AC, -10 speed",
	"13" => "Fainthearted: Flees upon ally death",
	"14" => "Racism: -1 Atk against those not of the hated house, +1 against them.",
	"15" => "Family Ties: +1 Atk when fighting alongside family",
	"16" => "Cautious: +1 AC, -5 Init",
	"17" => "Clean-living: Extended lifespan, vegan",
	"18" => "Gregarious: +2 Cha",
	"19" => "Sociopathic Serial Killer.",
	"20" => "Inner Peace: +2 Wis",
	"21" => "Purity of Purpose: +1 Str, Dex. +10% HP, rounding down.",
	"22" => "Irritable: -1 Atk",
	"23" => "Hermit: -1 to all stats when in a group.",
	"24" => "Athlete: +2 Str",
	"25" => "Nervous: -1 Atk",
	"26" => "Nihilistic: -2 Wis",
	"27" => "Oblivious: -4 Wis",
	"28" => "Optimistic:  :D ",
	"29" => "Attuned to the Pack: Take attacks of opportunities when adjacent allies do",
	"30" => "Passionless: -1 Child +2 Wis, -10% HP",
	"31" => "Heroic: +1 Atk, +1 AC.",
	"32" => "Pessimist: >:( ",
	"33" => "Frenetic: +4 Initiative, -1 AC",
	"34" => "Rebellious: YOU'RE NOT THE BOSS OF ME, MOM",
	"35" => "Alcoholic: +1 Str, -1 Dex, -1 Int, -1 AC.",
	"36" => "Shifty: +1 AC",
	"37" => "Sluggish: -1 AC",
	"38" => "Stalwart: +1 AC",
	"39" => "Hysterical: -1 Atk, -1 AC, -1 child",
	"40" => "Scatterbrained: -2 Wis",
	"41" => "Sound sleeper: +10% HP, hard to wake",
	"42" => "Wily: +1 AC",
	"43" => "Agreeable: Yeah!",
	"44" => "Well-traveled: +2 Int",
	"45" => "Honest: 'Yep, you're ugly.' ",
	"46" => "Musical prodigy: +1 Cha, (special abilities in fae bloodline)",
	"47" => "Cavalier: +1 melee damage, -1 Atk",
	"48" => "Exceptionally talkative:  :U  (jibberjabber intensifies)",
	"49" => "Empathetic:  +2 to Diplomacy and Sense Motive",
	"50" => "Thoughtful: +2 to Int",
	"51" => "Earnest",
	"52" => "Diehard: Bonus HP equal to CON mod. No death saves; just death.",
	"53" => "Exceptionally modest",
	"54" => "Principled",
	"55" => "Reckless: Your attacks have advantage. Attacks against you have advantage.",
	"56" => "Combat Masochist: +1 melee damage if you're not at full health",
	"57" => "Bloodlust: +1 melee damage if opponent isn't at full health",
	"58" => "Brawler: Proficiency with improvised weapons",
}
